name: thesis-pilot
channels:
  - pytorch-nightly
  - conda-forge
dependencies:
    - python=3.9
    - pip>=19.0
    - pytorch
    - torchvision
    - click = 8.1
    - matplotlib = 3.6
    - pydantic = 1.10
    - nox
    - PyYAML = 6.0
    - rich = 12.6
    - pybullet = 3.21
    - wandb = 0.13
    - protobuf = 3.20
    - gym = 0.21
    - jupyter
    - scikit-learn
    - scipy
    - pandas
    - pandas-datareader
    - pillow
    - tqdm
    - requests
    - h5py
    - pyyaml
    - flask
    - boto3
    - ipykernel
    - pip:
        - bayesian-optimization
        - gym == 0.21
        - kaggle
        - stable-baselines3[extra]
        - -e .
