name: thesis-pilot
channels:
  - pytorch-nightly
  - conda-forge
  - plotly
dependencies:
  - python=3.10
  - pip>=19.0
  - pytorch
  - torchvision
  - click = 8.1
  - matplotlib = 3.6
  - pydantic = 1.10
  - nox
  - PyYAML = 6.0
  - rich = 12.6
  - pybullet = 3.21
  - wandb = 0.13
  - protobuf = 3.20
  - jupyter
  - scikit-learn=1.2
  - scipy=1.9
  - pandas=1.5
  - pandas-datareader=0.10
  - tqdm=4.64
  - pyyaml=6.0
  - ipykernel
  - plotly=5.11
  - seaborn=0.12
  - tensorboard>=2.9
  - psutil  # SB3 extra
  - jupyterlab>=3.5
  - ipympl>=0.9  # Jupyter notebook plotting
  - pip:
      - opencv-python  # SB3 extra
      - stable-baselines3
      - -e .