name: thesis-pilot
channels:
  - pytorch-nightly
  - conda-forge
dependencies:
    - python=3.9
    - pip>=19.0
    - pytorch
    - torchvision
    - jupyter
    - scikit-learn
    - scipy
    - pandas
    - pandas-datareader
    - matplotlib
    - pillow
    - tqdm
    - requests
    - h5py
    - pyyaml
    - flask
    - boto3
    - ipykernel
    - slycot
    - control
    - pip:
        - bayesian-optimization
        - gym
        - kaggle
        - stable-baselines3[extra]
        - -e .
