
[tool.poetry]
name = "thesis_pilot"
version = "0.1.0"
description = "Preliminary work for my control systems with RL MSc thesis"
authors = ["lucas <lucas6eng@gmail.com>"]
license = "MIT"
include = [
    { path = "data", format = "sdist" },
    { path = "models", format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
tp = "thesis_pilot.__main__:main"